### ISSUE TITLE
got error if trying the example code in the wiki

### ISSUE THREAD

**Issue by ruiyang** [d11wtq/grizzl#9]
evaluate the following:
;; define a search index
(defvar *search-index* (grizzl-make-index '("one" "two" "three" "four")))

;; prompt the use to pick from the index
(grizzl-completing-read "Number: " *search-index*)

The error detail is:
Error in post-command-hook (#[nil \303\304 	#\305
"\207 [index *grizzl-current-result* prompt grizzl-search minibuffer-contents grizzl-display-result] 4]): (void-function delete-all-overlays)

I am running emacs 24.2.1, installed grizzl with built in package management. installed grizzl version: 20130810.1902

Please help to have a look if you can repro or give me some tips on debugging it on my machine.

Really want to find a similar mode like vim CtrlP mode. Grizzl is just what I want. Currently my projectile find file doesn't work, same error as above.

Thanks

**Comment by bbatsov** [comment]
I've updated the code to use true lexical scoping, which should solve this.
